# Identificacion del proyecto en SonarQube
sonar.projectKey=refactoring-u11
sonar.projectName=Pedidos Service — Refactorizacion U11
sonar.projectVersion=1.0

# Fuentes y binarios
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Reporte JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusiones
sonar.exclusions=**/*Application.java

# Servidor local
sonar.host.url=http://localhost:9000
sonar.qualitygate.wait=false
